### ISSUE TITLE
tcap API consistency

### ISSUE THREAD

**Issue by jkaivo** [gwsystems/composite#114]
Most tcap_\* functions take a pointer to a tcap as the first parameter. tcap_delete() takes a pointer to spd as its first argument. It should probably have its arguments swapped so the tcap pointer is first for consistency.

Also, tcap_delegate() takes its prio argument as an int rather than u16_t, which would be consistent with tcap_split() and the structure definition.

**Comment by gedare** [comment]
Most component invocations take spdid as the first argument (marshelled through stubs). Perhaps the other tcap functions should too?

**Comment by gparmer** [comment]
These are functions that are not part of a public API, and are really kernel internals.  So in that case, using the typical `noun_verb(struct noun *, ...)` is appropriate.
