### ISSUE TITLE
transfering all or any amount of budgets from currently active tcap

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/composite#204]
Transferring away all the remaining budget or for that matter, any amount from the currently active tcap, (especially in tcap_transfer case) will make the current execution to run with much less or zero budget for as long until the expected timer to fire for this active tcap. (This leads to a lot of unaccounted cycles in the system, if this happens often or if the active tcap before transferring had a lot of budget.)

Need to fix this by adding budget expended logic to switch away to another eligible tcap or at the least to update the timer interrupt to fire at the earliest.

**Comment by phanikishoreg** [comment]
PR #209 Commit: 8a4a7a6a16364ecdfae5276e492914c5a09787fc fixes this issue

**Comment by Others** [comment]
Closed by #209
