### ISSUE TITLE
overflow of budgets

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/composite#205]
Transferring budgets to a tcap, could cause the `tcap_res_t` to overflow or even promote it to a INF budget tcap. 

Need to handle by having a maximum possible budget, like `MAX=INF - 1`. 
Only transfer up to the MAX amount and return, but this may not be consistent with the current implementation which doesn't allow transferring budgets less than expected cycles (ex: if a tcap has 100 cycles and the transfer request was for 150 cycles, it returns error currently).

For consistency, either error out in both cases or transfer as much as `possible/available`.

**Comment by phanikishoreg** [comment]
PR #209 Commit: 39e9c9642d9cbaaf8002adf13438e6ff1e38d6d9 fixes this issue.

**Comment by Others** [comment]
Fixed by #209
