### ISSUE TITLE
possibility of not setting a oneshot/deadline timer

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/composite#206]
With some edge-cases checks in `tcap_timer_update`, it is possible to not set a oneshot/deadline timer. And also, if the timers are not far enough into the future, possibility (especially with ONESHOT timers conversions) of APIC logic may not set timers, this could cause currently active tcap to execute for far longer than it should, without explicit tcap switches, this could even cause the current tcap to execute forever. 

Need to set a minimum granularity for timer sets and all edge-cases should be handled to either trigger the "budget expended" logic immediately or to set a earliest deadline/oneshot timer so that budget expended logic gets triggered at the earliest possible time.

**Comment by phanikishoreg** [comment]
PR #209 Commit: b48af6b8c9c11228fcc190f60780c153d1c9bea3 has a fix for this issue.

**Comment by Others** [comment]
Fixed by #209 (can you verify @phanikishoreg?)

**Comment by phanikishoreg** [comment]
It is fixed, yes.
