### ISSUE TITLE
Create default cos_compinfo initialization functions

### ISSUE THREAD

**Issue by vnitu02** [gwsystems/composite#266]
`cos_meminfo_init` and `cos_compinfo_init`

**Comment by Others** [comment]
@phanikishoreg I think we might of talked about this before, specifically `meminfo`. Do you mind jotting down your thoughts here?

**Comment by phanikishoreg** [comment]
We have default for `cos_compinfo_init` through `cos_defkernel_api` library. 
For `cos_meminfo_init`, we need to discuss about, I don't remember talking sufficiently deep into this.

In my opinion, the `cos_meminfo_init` usage is:
1. For a component that is a memory manager, untyped memory has to be the memory available to the system and with an untyped pagetable capability(default: BOOT_CAPTBL_SELF_UNTYPED_PT). 
2. For any other component, the untyped must be 0 without an untyped pagetable capability unless memory manager grants some untyped pages to it. 

I think you mentioned it is to do `posix` library init at the bootup, but I think I still don't have a full context. But I'm still not sure if the default API for either are going to do the right thing we want for either.

We need a deeper discussion into the initialization of the core kernel libraries and also `sl` for bootup sequence.
