### ISSUE TITLE
Cleanup micro_booter to provide meaningful output

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/composite#293]
Micro_booter is used to both unit test and benchmarking of kernel api. 
For unit tests, it spits out a lot of log that is not readable to a lot of people.
We need to fix the output to print SUCCESS/FAILURE in the unit test cases.

In addition to that, I think we have code both for unit test and performance test in the same file, it would be great either to have to separate tests or to at least have them in two separate files in the same test directory.

**Comment by Others** [comment]
Closing this -- we need to make a bigger issue about unit tests and microbenchmarks in composite. The output/format needs to be consistent across all components, not just the microbooter.
