### ISSUE TITLE
Update microbenchmarks to include Tcap benchmarking and WCMT

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/composite#294]
I've been testing TCap api by manually merging from one branch to an updated for the papers related to TCaps.

Need to move them to the mainline repo.
Also, include the measurements for Worst Case Measured Time with a kernel introspection to flush hardware caches!

**Comment by Others** [comment]
Closing this -- we need to make a bigger issue about unit tests and microbenchmarks in composite. The output/format needs to be consistent across all components, not just the microbooter.
