### ISSUE TITLE
HPET (HW? probably not the driver) not working on Intel Core 2 Duo 

### ISSUE THREAD

**Issue by phanikishoreg** [gwsystems/composite#318]
This is probably a issue with the hardware but I can't confirm as this is the only PC of that type in the lab.
CPU Information from BIOS:
```
Dell Optiplex 755
Processor Type: Intel Core 2 Duo CPU E6750 @ 2.66GHz
 Clock Speed = 2.66 GHz
 Bus Speed = 1333 MHz
 L2 Cache = 4MB
 ID: 000006FB 
Family = 06, Model = 0F, Stepping = B
Microcode version: 000000B3
Multiple core capable: Yes (dual)
Hyperthreading capable: No
64-bit Tech: Yes (Intel EM64T)
```
This could be a problem on that specific HW or on that family of processors or Dell model.
I commented the micro_booter to not test timer related cases and the remaining tests just work fine on this HW. 
The issue is probably not related to Composite s/w, so will just leave this note for future reference.

**Comment by gparmer** [comment]
HPET isn't as important anymore.  However should add dynamic checks to see if it is present on the hardware.
