### ISSUE TITLE
When using sl lib, all sl libraries must be linked, even when just a single lib is needed

### ISSUE THREAD

**Issue by RobertGiff** [gwsystems/composite#338]
If a component needs lib posix, then that component must link in all sl libraries despite never using any of them.

**Comment by Others** [comment]
This isn't really a solvable issue with the current implementation of libposix. We provide posix thread creation, so we can't not use sl.

**Comment by RobertGiff** [comment]
Okay, so it _might_ use them, which is fine, but as it currently stands, **all** sl libraries must be linked in. @phanikishoreg designed them as separate libraries so they shouldn't have necessary dependencies between them all.

**Comment by Others** [comment]
sl is supposed to be pluggable, so you can swap in different versions of libraries. This does not mean you don't need all of the libraries. What do you want to do that isn't possible?

If it's not link sl, we need a different version of libposix. If you want to link less sl, that's an sl design issue.

**Comment by RobertGiff** [comment]
@Others renamed issue to focus on the necessity for all lib sl libraries. @phanikishoreg told me in person that one shouldn't have to use all of them, so I believe there is still an issue with sl design itself.

**Comment by phanikishoreg** [comment]
There must be some miscommunication @RobertGiff !
I really meant `sl` should not be linked to when we're in an application (not a scheduler).
Like `pthread` is a library, we should have the posix layer that is required for `thread management, tls management and futexes` be a separate library that may not be linked to if an application is just single threaded (like our udpserver) and all that it does is for example use SOCKET API. 

Also, we need a version of `posix` that uses `sched` interface and not link to sl for a component that is not a scheduler and uses a scheduling interface instead. It should be like we have `sl_raw` and `sl_capmgr`, we need `posix_sched` which uses scheduling interface and uses `capmgr` for TLS stuff where necessary! 

Other way is:
We need to overload `capmgr -> really memmgr` and `sched` interfaces so the posix implementation remains the same and uses the capmgr/sched interface API. A component then either links to all required libraries or specifies dependencies on these interfaces for invocations.
